// Mock data for the Knowledge Hub UI — same pattern as the rest of the app
// (src/lib/mock/*): real schema and query layer already exist, but the UI
// runs on typed fixtures until a Google Drive integration is actually
// connected. Swap `src/app/(app)/knowledge/page.tsx` from this to
// `listFolders`/`listDocuments` (src/lib/knowledge/repository.ts) once it is.
import type { KnowledgeDocument, KnowledgeFolder } from "./types";

export const mockKnowledgeFolders: KnowledgeFolder[] = [
  { id: "fld-production", externalId: "ext-production", parentId: null, name: "Production", path: "Production", category: "production" },
  { id: "fld-hr", externalId: "ext-hr", parentId: null, name: "HR", path: "HR", category: "hr" },
  { id: "fld-marketing", externalId: "ext-marketing", parentId: null, name: "Marketing", path: "Marketing", category: "marketing" },
  { id: "fld-finance", externalId: "ext-finance", parentId: null, name: "Finance", path: "Finance", category: "finance" },
  { id: "fld-operations", externalId: "ext-operations", parentId: null, name: "Operations", path: "Operations", category: "operations" },
];

export const mockKnowledgeDocuments: KnowledgeDocument[] = [
  {
    id: "doc-sop-filling",
    externalId: "ext-sop-filling",
    folderId: "fld-production",
    name: "SOP - Filling Jars",
    category: "production",
    fileType: "doc",
    url: "https://drive.google.com/file/d/mock-sop-filling/view",
    ownerName: "Molly Hansen",
    lastModifiedAt: "2026-06-18T09:00:00+12:00",
    syncStatus: "synced",
  },
  {
    id: "doc-sop-labels",
    externalId: "ext-sop-labels",
    folderId: "fld-production",
    name: "SOP - Applying Labels",
    category: "production",
    fileType: "doc",
    url: "https://drive.google.com/file/d/mock-sop-labels/view",
    ownerName: "Molly Hansen",
    lastModifiedAt: "2026-06-18T09:10:00+12:00",
    syncStatus: "synced",
  },
  {
    id: "doc-sop-packing",
    externalId: "ext-sop-packing",
    folderId: "fld-production",
    name: "SOP - Packing Orders",
    category: "production",
    fileType: "doc",
    url: "https://drive.google.com/file/d/mock-sop-packing/view",
    ownerName: "Molly Hansen",
    lastModifiedAt: "2026-06-20T14:30:00+12:00",
    syncStatus: "synced",
  },
  {
    id: "doc-staff-handbook",
    externalId: "ext-staff-handbook",
    folderId: "fld-hr",
    name: "Staff Handbook",
    category: "hr",
    fileType: "pdf",
    url: "https://drive.google.com/file/d/mock-staff-handbook/view",
    ownerName: "Molly Hansen",
    lastModifiedAt: "2026-04-02T11:00:00+12:00",
    syncStatus: "synced",
  },
  {
    id: "doc-leave-policy",
    externalId: "ext-leave-policy",
    folderId: "fld-hr",
    name: "Leave Policy",
    category: "hr",
    fileType: "doc",
    url: "https://drive.google.com/file/d/mock-leave-policy/view",
    ownerName: "Molly Hansen",
    lastModifiedAt: "2026-04-02T11:05:00+12:00",
    syncStatus: "synced",
  },
  {
    id: "doc-brand-guidelines",
    externalId: "ext-brand-guidelines",
    folderId: "fld-marketing",
    name: "Brand Guidelines",
    category: "marketing",
    fileType: "pdf",
    url: "https://drive.google.com/file/d/mock-brand-guidelines/view",
    ownerName: "Molly Hansen",
    lastModifiedAt: "2026-03-11T16:20:00+12:00",
    syncStatus: "synced",
  },
  {
    id: "doc-product-photography",
    externalId: "ext-product-photography",
    folderId: "fld-marketing",
    name: "Product Photography",
    category: "marketing",
    fileType: "folder",
    url: "https://drive.google.com/drive/folders/mock-product-photography",
    ownerName: "Molly Hansen",
    lastModifiedAt: "2026-05-30T10:00:00+12:00",
    syncStatus: "synced",
  },
  {
    id: "doc-supplier-forms",
    externalId: "ext-supplier-forms",
    folderId: "fld-finance",
    name: "Supplier Forms",
    category: "finance",
    fileType: "sheet",
    url: "https://drive.google.com/file/d/mock-supplier-forms/view",
    ownerName: "Molly Hansen",
    lastModifiedAt: "2026-05-14T13:45:00+12:00",
    syncStatus: "synced",
  },
  {
    id: "doc-opening-checklist",
    externalId: "ext-opening-checklist",
    folderId: "fld-operations",
    name: "Opening Checklist",
    category: "operations",
    fileType: "doc",
    url: "https://drive.google.com/file/d/mock-opening-checklist/view",
    ownerName: "Ange",
    lastModifiedAt: "2026-07-01T08:00:00+12:00",
    syncStatus: "synced",
  },
  {
    id: "doc-closing-checklist",
    externalId: "ext-closing-checklist",
    folderId: "fld-operations",
    name: "Closing Checklist",
    category: "operations",
    fileType: "doc",
    url: "https://drive.google.com/file/d/mock-closing-checklist/view",
    ownerName: "Charlie",
    lastModifiedAt: "2026-07-01T08:05:00+12:00",
    syncStatus: "synced",
  },
];
