// Mock data for Supplier Records — same pattern as src/lib/knowledge/mock.ts:
// real schema + sync pipeline already exist (see repository.ts, sync.ts), but
// the UI runs on typed fixtures shaped exactly like the Sheet columns until a
// Google account is actually connected and a sync has run. Swap the API
// routes under app/api/supplier-records from this to repository.ts once it is.
import type { SupplierRecordItem, SupplierRecordSupplier } from "./types";

export const mockSupplierRecordSuppliers: SupplierRecordSupplier[] = [
  {
    id: "sup-clearview",
    name: "Clearview Glass Co.",
    contactPerson: "Steve Lombardi",
    email: "steve@clearviewglass.co.nz",
    phone: "09 555 0182",
    website: "www.clearviewglass.co.nz",
    address: "12 Foundry Rd, Henderson, Auckland",
    productsSupplied: "Glass jars & lids, all sizes",
    notes: "Reliable on lead times; ask for the textured-lid range for gift sets.",
    lastUpdated: "2026-06-28",
  },
  {
    id: "sup-silverdale-print",
    name: "Silverdale Print & Label",
    contactPerson: "Nadia Osei",
    email: "nadia@silverdaleprint.co.nz",
    phone: "09 555 0234",
    website: "www.silverdaleprint.co.nz",
    address: "4 Print Lane, Silverdale, Auckland",
    productsSupplied: "Labels, gift tags, retro print stock",
    notes: "Can rush small runs in 48 hours for an extra $40.",
    lastUpdated: "2026-07-05",
  },
  {
    id: "sup-packright",
    name: "PackRight NZ",
    contactPerson: "Tom Baker",
    email: "tom@packright.co.nz",
    phone: "09 555 0310",
    website: "www.packright.co.nz",
    address: "88 Carton Ave, Penrose, Auckland",
    productsSupplied: "Kraft boxes, tissue paper, void fill",
    notes: "Compliance paperwork overdue for renewal — chase before next big order.",
    lastUpdated: "2026-06-15",
  },
  {
    id: "sup-sweetfillings",
    name: "Sweet Fillings Ltd",
    contactPerson: "Rachel Yun",
    email: "rachel@sweetfillings.co.nz",
    phone: "07 555 0421",
    website: "www.sweetfillings.co.nz",
    address: "21 Sugar St, Hamilton",
    productsSupplied: "Bulk confectionery fillings & inclusions",
    notes: "Minimum order 25kg per flavour.",
    lastUpdated: "2026-07-01",
  },
  {
    id: "sup-oki",
    name: "OKI Data NZ",
    contactPerson: "Support Team",
    email: "support@okidata.co.nz",
    phone: "0800 654 000",
    website: "www.okidata.co.nz",
    address: "15 Business Pde, Auckland",
    productsSupplied: "Printer hardware, toner, label rolls",
    notes: "",
    lastUpdated: "2026-05-20",
  },
];

export const mockSupplierRecordItems: SupplierRecordItem[] = [
  {
    id: "item-jar-250",
    name: "250ml Glass Jar w/ Lid",
    category: "Glass Jars",
    supplierName: "Clearview Glass Co.",
    supplierContact: "steve@clearviewglass.co.nz",
    sku: "CVG-250",
    costPrice: 1.85,
    packSize: "24/carton",
    notes: "Standard lolly jar size.",
    lastUpdated: "2026-06-28",
  },
  {
    id: "item-jar-500",
    name: "500ml Glass Jar w/ Lid",
    category: "Glass Jars",
    supplierName: "Clearview Glass Co.",
    supplierContact: "steve@clearviewglass.co.nz",
    sku: "CVG-500",
    costPrice: 2.4,
    packSize: "12/carton",
    notes: "Used for the corporate gift range.",
    lastUpdated: "2026-06-28",
  },
  {
    id: "item-label-retro",
    name: "Retro Lolly Jar Label (Sheet)",
    category: "Labels",
    supplierName: "Silverdale Print & Label",
    supplierContact: "nadia@silverdaleprint.co.nz",
    sku: "SPL-LBL-01",
    costPrice: 0.32,
    packSize: "500/roll",
    notes: "",
    lastUpdated: "2026-07-05",
  },
  {
    id: "item-gift-tag",
    name: "Cheeky Gift Tag",
    category: "Labels",
    supplierName: "Silverdale Print & Label",
    supplierContact: "nadia@silverdaleprint.co.nz",
    sku: "SPL-TAG-04",
    costPrice: 0.18,
    packSize: "250/pack",
    notes: "Matches the corporate gift range branding.",
    lastUpdated: "2026-07-05",
  },
  {
    id: "item-box-small",
    name: "Kraft Gift Box (Small)",
    category: "Packaging & Boxes",
    supplierName: "PackRight NZ",
    supplierContact: "tom@packright.co.nz",
    sku: "PR-BOX-S",
    costPrice: 1.1,
    packSize: "50/bundle",
    notes: "",
    lastUpdated: "2026-06-15",
  },
  {
    id: "item-box-large",
    name: "Kraft Gift Box (Large)",
    category: "Packaging & Boxes",
    supplierName: "PackRight NZ",
    supplierContact: "tom@packright.co.nz",
    sku: "PR-BOX-L",
    costPrice: 1.65,
    packSize: "25/bundle",
    notes: "",
    lastUpdated: "2026-06-15",
  },
  {
    id: "item-tissue",
    name: "Tissue Paper - Retro Print",
    category: "Packaging & Boxes",
    supplierName: "PackRight NZ",
    supplierContact: "tom@packright.co.nz",
    sku: "PR-TIS-01",
    costPrice: 0.09,
    packSize: "200/pack",
    notes: "",
    lastUpdated: "2026-06-15",
  },
  {
    id: "item-filling-pineapple",
    name: "Pineapple Lump Filling (Bulk)",
    category: "Confectionery & Ingredients",
    supplierName: "Sweet Fillings Ltd",
    supplierContact: "rachel@sweetfillings.co.nz",
    sku: "SF-PINE-25",
    costPrice: 6.5,
    packSize: "25kg bag",
    notes: "Bestseller — keep 2 bags minimum in stock.",
    lastUpdated: "2026-07-01",
  },
  {
    id: "item-filling-chocfish",
    name: "Chocolate Fish Filling (Bulk)",
    category: "Confectionery & Ingredients",
    supplierName: "Sweet Fillings Ltd",
    supplierContact: "rachel@sweetfillings.co.nz",
    sku: "SF-CFISH-25",
    costPrice: 8.2,
    packSize: "25kg bag",
    notes: "",
    lastUpdated: "2026-07-01",
  },
  {
    id: "item-oki-toner",
    name: "OKI Pro9542 Toner Cartridge",
    category: "Printer & Label Hardware",
    supplierName: "OKI Data NZ",
    supplierContact: "support@okidata.co.nz",
    sku: "OKI-TON-9542",
    costPrice: 145,
    packSize: "1 unit",
    notes: "",
    lastUpdated: "2026-05-20",
  },
  {
    id: "item-oki-label-roll",
    name: "OKI Label Roll - Gloss",
    category: "Printer & Label Hardware",
    supplierName: "OKI Data NZ",
    supplierContact: "support@okidata.co.nz",
    sku: "OKI-LBL-GLS",
    costPrice: 24,
    packSize: "1 roll",
    notes: "",
    lastUpdated: "2026-05-20",
  },
];
